### ISSUE TITLE
Paper Release time

### ISSUE THREAD

**Issue by Mountchicken** [zhaominyiz/STIRER#1]
Hello there

Just wondering when will the paper be released.😁

**Comment by zhaominyiz** [comment]
Hi,
We are now preparing for the camera-ready version and we plan to release the full paper, codes, and models within one week. You may check the repo at weekend:)

**Comment by zhaominyiz** [comment]
Hi,
I have uploaded the paper (pdf). The code and checkpoints will be released within one week :)

**Comment by llvhjgtdl** [comment]
> Hi, I have uploaded the paper (pdf). The code and checkpoints will be released within one week :)
When will the code be released?

**Comment by zhaominyiz** [comment]
Full code has been uploaded :)
